gpio:
  start:
    trigger: 17
    echo: 27
  split1:
    trigger: 22
    echo: 23
  split2:
    trigger: 24
    echo: 25
  finish:
    trigger: 26
    echo: 19

calibration:
  thresholds:
    start: 20
    split1: 20
    split2: 20
    finish: 20

detection:
  history_size: 5
  min_passage_duration_ms: 50
  max_passage_duration_s: 5.0

data:
  db_file: ./data/runs.db

web:
  host: "0.0.0.0"
  port: 5000
